---

name: Install

on:
  push:

jobs:

  install:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        tool: [poetry, uv]
        cdf: ['1.7.1.post2', '1.7.2', '1.7.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Update tools
        run: |
          pip install -U pip
          pip install -U pipx
          pipx install ${{ matrix.tool }}

      - name: Print versions
        run: |
          python --version
          pip --version
          pipx --version
          ${{ matrix.tool }} --version

      - name: Set version
        run: ${{ matrix.tool }} add "netcdf4==${{ matrix.cdf }}"

      - name: Install via poetry
        if: ${{ matrix.tool == 'poetry' }}
        run: POETRY_INSTALLER_NO_BINARY=:all: poetry install

      - name: Install via uv
        if: ${{ matrix.tool == 'uv' }}
        run: UV_NO_BUILD=1 uv sync

      - name: Test
        run: ${{ matrix.tool }} run python test.py
